base: ghcr.io/vanilla-os/desktop:main
name: T2 Orchid
id: vanilla-nvidia
labels:
  maintainer: LED-esma
args:
  DEBIAN_FRONTEND: noninteractive
runs:
- echo 'APT::Install-Recommends "0";' > /etc/apt/apt.conf.d/01norecommends

modules:
- name: init-setup
  type: shell
  commands:
  - lpkg --unlock
  - apt update

- name: t2-packages
  type: apt
  source:
    type: git
    url: https://adityagarg8.github.io/t2-ubuntu-repo/
    packages:
    - t2-kernel-script-debian
    - tiny-dfr
 
- name: vanilla-tools
  type: shell
  source:
    type: tar
    # switch to production build once in production
    url: https://github.com/Vanilla-OS/vanilla-tools/releases/download/continuous/vanilla-tools.tar.gz
  commands:
  - mkdir -p /usr/bin
  - cp /sources/vanilla-tools/nrun /usr/bin/nrun
  - chmod +x /usr/bin/nrun

- name: cleanup
  type: shell
  commands:
  - apt autoremove -y
  - apt clean
  - lpkg --lock
