name: Vib Build

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
  schedule:
    - cron: '0 */12 * * *'

    
env:
  REGISTRY_USER: ${{ github.actor }}
  REGISTRY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}

permissions:
  contents: write
  packages: write  
    
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Vib
      run: |
        wget https://github.com/Vanilla-OS/Vib/releases/download/v0.3.1/vib
        chmod +x vib
        ./vib build recipe.yml

    - name: Build the Docker image
      run: docker image build -f Containerfile --tag ghcr.io/led-esma/t2desktop:main .

    - name: Publish to GHCR
      run: |
       docker login ghcr.io -u ${{ env.REGISTRY_USER }} -p ${{ env.REGISTRY_PASSWORD }}
       docker image push "ghcr.io/led-esma/t2desktop:main"

