name: Vib Build

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: write
  packages: write  
    
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Vib
      run: |
        wget https://github.com/Vanilla-OS/Vib/releases/download/v0.3.1/vib
        chmod +x vib
        ./vib build recipe.yml

    - name: Build the Docker image
      run: docker image build -f Containerfile --tag led-esma .

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    # Push the image to GHCR (Image Registry)
    - name: Push To GHCR
      run: docker image push "led-esma"